version: '3.8'
services:
  email-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sbis-notify-calls
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_FILE=/app/logs/bot.log
      - TZ=Europe/Moscow
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-email-bot

volumes:
  bot-logs:
    driver: local