# =======================================================
# Docker Compose для Email to Telegram Bot
# Оптимизирован для правильной работы логирования
# =======================================================
services:
  # ===============================================
  # Основной сервис бота
  # ===============================================
  email-telegram-bot:
    # Образ для production
    image: ghcr.io/vaqybin/sbisnotifycalls:latest
    
    # Для разработки используйте сборку из локального Dockerfile
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   target: production
    
    container_name: email-telegram-bot
    restart: unless-stopped
    
    # ===============================================
    # НАСТРОЙКИ ЛОГИРОВАНИЯ
    # ===============================================
    # Настройка драйвера логирования Docker
    logging:
      driver: "json-file"  # Стандартный драйвер, поддерживает docker logs
      options:
        max-size: "10m"    # Максимальный размер одного лог-файла
        max-file: "3"      # Количество файлов для ротации
        # Для больших объемов логов можно увеличить:
        # max-size: "50m"
        # max-file: "5"
    
    # ===============================================
    # ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
    # ===============================================
    env_file:
      - .env
    
    # Дополнительные переменные для стабильной работы логирования
    environment:
      # Принудительное отключение буферизации Python
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONIOENCODING=utf-8
      
      # Настройки локализации для корректной работы на Windows/Linux/MacOS
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      
      # Часовой пояс (настройте по вашему региону)
      - TZ=Europe/Moscow
      
      # Дополнительные настройки для отладки (закомментируйте для продакшена)
      # - PYTHONDEBUG=1
    
    # ===============================================
    # МОНТИРОВАНИЕ ТОМОВ
    # ===============================================
    volumes:
      # Том для логов приложения (файловое логирование)
      - bot_logs:/app/logs
      
      # Для разработки: монтирование исходного кода (раскомментируйте если нужно)
      # - .:/app:ro
    
    # ===============================================
    # СЕТЕВЫЕ НАСТРОЙКИ
    # ===============================================
    networks:
      - bot_network
    
    # ===============================================
    # ОГРАНИЧЕНИЯ РЕСУРСОВ
    # ===============================================
    deploy:
      resources:
        limits:
          memory: 512M      # Увеличено для стабильной работы
          cpus: '1.0'       # Увеличено для обработки логов
        reservations:
          memory: 256M
          cpus: '0.2'
    
    # ===============================================
    # МОНИТОРИНГ ЗДОРОВЬЯ
    # ===============================================
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys; print(\"Bot healthcheck OK\", flush=True); sys.exit(0)'"]
      interval: 30s
      timeout: 15s          # Увеличено время ожидания
      retries: 3
      start_period: 60s     # Увеличено время первоначального запуска

# =======================================================
# НАСТРОЙКИ ТОМОВ
# =======================================================
volumes:
  bot_logs:
    driver: local
    # Настройки драйвера для Windows совместимости
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/logs  # Создает папку logs в текущей директории
    # Для Linux/MacOS можно использовать стандартные именованные тома:
    # (закомментируйте driver_opts выше и раскомментируйте ниже)
    # labels:
    #   - "project=email-telegram-bot"
    #   - "type=logs"

# =======================================================
# НАСТРОЙКИ СЕТЕЙ
# =======================================================
networks:
  bot_network:
    driver: bridge
    # Настройки для лучшей производительности сети
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    # labels:
    #   - "project=email-telegram-bot"

# =======================================================
# ДОПОЛНИТЕЛЬНЫЕ СЕРВИСЫ ДЛЯ РАЗРАБОТКИ
# =======================================================
# Раскомментируйте для добавления веб-интерфейса логов (опционально)
# log-viewer:
#   image: amir20/dozzle:latest
#   container_name: email-bot-logs
#   restart: unless-stopped
#   ports:
#     - "8080:8080"
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock:ro
#   environment:
#     DOZZLE_LEVEL: info
#     DOZZLE_TAILSIZE: 300
#   networks:
#     - bot_network

# =======================================================
# ПРОФИЛИ ДЛЯ РАЗНЫХ СРЕД
# =======================================================
# Для development окружения:
# docker-compose --profile dev up
# 
# profiles:
#   - production  # По умолчанию

# Для development можно добавить дополнительные настройки:
# services:
#   email-telegram-bot-dev:
#     profiles:
#       - dev
#     extends: email-telegram-bot
#     environment:
#       - LOG_LEVEL=DEBUG
#       - CHECK_INTERVAL=60
#     volumes:
#       - .:/app:ro